### ISSUE TITLE
Can i use this package for person recognition?

### ISSUE THREAD

**Issue by alex-rsk** [VlSomers/keypoint_promptable_reidentification#9]
Hello, and thank you for great work.

I have a specific task -  given a series of images, taken with some interval 5-10 seconds. I need to recognize 3-5 known people on them. Their faces are often overlapped with furniture, doors, sometimes other people. So I can't rely to face recognition.

Please tell, is this package applicable for such task ?

**Comment by VlSomers** [comment]
Yes it might work for your use case, but you will maybe need to retrain the model to better fit your domain.

**Comment by alex-rsk** [comment]
Thank you, I'll try then.
